### ISSUE TITLE
Publish to npm ecosystem in es5 version

### ISSUE THREAD

**Issue by artificis** [jdalrymple/node-gitlab-api#14]
This would not be necessary if the package is used in node.js server side.
But I'm currently trying this in React.js app using `create-react-app`. And it complains while building process, due to the usage of `async/await` syntax.

Can we publish this in es5 version?

**Comment by jdalrymple** [comment]
I don't know if this is a good idea. This library is targeted for server side JavaScript, which should be run on the LTE version of nodejs. Currently the latest LTE is 8.91 and es6 was given support as of 7.6, as far as i know. Though I don't know of any downsides to transcompiling down to es5, besides restricting the library to only es5 modules in the future, I believe modifying a library to support your use of the code is a slippery slope.

Isnt the create-react-app client side?

**Comment by clthck** [comment]
I knew it was mainly targeted for server side JS ( can tell from its name ). I looked for a good gitlab API npm package I can consume in my frontend react app with API v4 support and this one was the most comprehensive and working one for me. It worked fine in development mode on my local machine, until I tried to build for production usage.

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

If you think this is going to take a while to do so in your side, that is fine. I'm already using a forked version of this repo and using transpiled es5 version directly from my github repo.

So just keep posted once you decide you'd go this way and I will delete my forked repo and use this original one.

Thanks for your hard work!

**Comment by jdalrymple** [comment]
Fair enough! Thank you for helping me make the library better!! I also know there has been talk about including the latest uglify version into create-react-app which would fix the inclusion of es6 modules client side

**Comment by jdalrymple** [comment]
A way to do this would be to release a node-gitlab-api/es5 export, which would be a babel compiled version?

**Comment by artificis** [comment]
We can keep es6 version inside `src` folder, add it to `.npmignore` file, and keep transpiled version into `lib` folder, add that to `.gitignore`. Also need to change `main` entry in `package.json` so that it points to `lib/index.js`, not `src/index.js`. I saw most people do this way.

**Comment by jdalrymple** [comment]
In that case only the es5 version would be exported then no? I was thinking along the lines of:

```javascript
// For es5 version
const Gitlab = require('node-gitlab-api/es5') 

// And for standard es6

const Gitlab = require('node-gitlab-api')
```

Or is that confusing?

**Comment by artificis** [comment]
That could be an option too. But I think we'd better follow conventions. Do
you see any specific need to export in es6 version? Most popular packages
export in es5 version for the sake of compatibility.

**Comment by jdalrymple** [comment]
Since this is server directed, and es6 is officially supported server side, there is no reason to support anything less. The es5 compilation is only for those trying to use this client side without having to handle the conversion themselves. The popular projects were developed before es6 was officially supported so understandably they would support both in that fashion. This was meant as a compromise.

**Comment by jdalrymple** [comment]
Is the general consensus that node packages regardless of where they are directed should be standard es5? I haven't found any consensus on this :( and i have looked. Would rather abide by some standard if i can lol but also not affect all the people that are currently using it.

**Comment by artificis** [comment]
Publishing in es5 won't affect existing users at all. Everything just works in es5 version as well, whether it's about `import` or `require`.

**Comment by jdalrymple** [comment]
Thinking about adding this stuff today, but i still have some reservations. I don't think it makes sense for a library to target lower versions of JS because the compatibility really depends on the user who is using the packages. We shouldn't be transpiling for the sake of transpiling. Yes es5 is more commonly supported, but who is to say someone is using a very old browser where es5 isnt supported? Then the user of the library will have to transpile the code even further which defeats the purpose of the libraries author transpiling in the first place. I think this decision should be on the user of the library.

**Comment by jdalrymple** [comment]
In the mean time, I've release a es5 version under a subdirectory.

**Comment by jdalrymple** [comment]
Closing for now
