### ISSUE TITLE
Republishing under more intuitive name

### ISSUE THREAD

**Issue by jdalrymple** [jdalrymple/node-gitlab-api#30]
While i was looking at the package on npm today, i noticed it is actually hard to come by when you do a simple search for gitlab. I was thinking maybe using a different package name would help in this regard, something like gitlab-plus ? 

Thoughts?

**Comment by arsdehnel** [comment]
Interesting. It’s worth considering if that alone would help. I know for me I landed on it because it is up-to-date (others are months or years behind) and it is async/await ready. What about gitlab-async or something? 

I’ll be honest that gitlab-plus doesn’t tell me much. Just sounds purely like the name was taken and this project needed something to make it unique. ES6 support is a differentiator but calling it gitlab-es6 will quickly get out of date (since we’re on es2018 now or whatever).

**Comment by jdalrymple** [comment]
😂 well it was purely because it was taken. I don't know if it will do much but it will def help with the initial search. Yea es6 will get old fast, and async is almost standard at this point so I feel like that will get outdated soon as well

**Comment by jdalrymple** [comment]
Actually i dont know how the 'official' library gets so many downloads smh, I used it before making this library but it was so outdated :s, I dont want others to have to go through that expereince lol

**Comment by jdalrymple** [comment]
Only corny names are coming to mind:

- gitlaboratory
- gitlab-plus
- gitlab...something

**Comment by bufferoverflow** [comment]
or just gitlab-ce?

**Comment by jdalrymple** [comment]
But technically, the library would work with the enterprise eddition as well.

**Comment by bufferoverflow** [comment]
Yes, I know. Do you have some Enterprise Edition only features within the node wrapper?

**Comment by jdalrymple** [comment]
Not exactly, the wrapper is generic. If you use it with CE only the features available in ce will work, likewise with ee, but they are all exposed in the same library.

**Comment by jdalrymple** [comment]
- gitlab-prime 
- gitlab-ae ( or some letter suffix that stands for all all versions )

**Comment by arsdehnel** [comment]
My vote would be to just keep the name as it is and work on making a few changes/tweaks to make it better to use.  I think those things are happening (#33 , #38 both come to mind).  Also wondering if a structure for documentation might help increase use and therefore increase google ranking.  As I mentioned in #38 the docs at https://octokit.github.io/rest.js/ are nice and clear and simple to reference. 

Couple reactions to the above names: 

- `gitlab-ce` I agree it would be off-putting to me as an EE user, thinking there are features that are not included in here because of the name.

- `gitlab-prime`, `gitlab-plus` and `gitlab-ae` almost seems like there are some _other_ subscription levels for gitlab that I just don't know about or something.

**Comment by erquhart** [comment]
How about gitlab-js?

**Comment by jrop** [comment]
I have also seen some libraries add a suffix: e.g.: `gitlab2`

**Comment by jdalrymple** [comment]
I think they've mentioned switching the main package to point to this repo but I'm unsure what progress is with that atm

**Comment by jdalrymple** [comment]
I was just given maintainer access to the gitlab npm package. Will be releasing 3.0.0 within the next day under that npm package and deprecating node-gitlab-api with a message to use the gitlab package

**Comment by jdalrymple** [comment]
Release the newest version under node-gitlab-api and gitlab. Thinking i should deprecate the node-gitlab-api package now that its published under gitlab. Thoughts?
