### ISSUE TITLE
`Humps.decamelizeKeys` might be too opinionated

### ISSUE THREAD

**Issue by Mr-Wallet** [jdalrymple/node-gitlab-api#58]
I notice that the `body` and `qs` parameters are being run through this method.

As an immediate fix, this should at least be documented more clearly so that no one gets stuck on it. However it seems like a very opinionated way about how the package should be used and what requests should look like. If I used a camel-case key in my `qs` parameter, I would not expect an underscore to be inserted in the key; I would expect it to be used literally, at least by default.

To me it seems like a better pattern would be to naively use the options as-given, and if the programmer wants de-camelizing, they can run their own objects through hump before sending them to this package. This would also bring the package size down if hump can be removed as a dependency.

**Comment by jdalrymple** [comment]
I thought about this before adding the dependency. The gitlab api, as far as I could tell, only supports snake cased parameters and because the library is only interacting with that API, ensuring the parameters were snake cased through humps allowed developers to stick with a JavaScript standard of using camelcase without having to worry about reformatting when using the library. 

Without humps there ended up being inconsistencies  in the library where everything was camelcase except for a the defined option params.

I feel like the size of the library is negligible,  and because the library is only interacting with the API of gitlab, their is not chance of conflict with the casing the query params/ body params. 

But I do agree the params you enter should not be modified at least not inconsistently. I would much rather stick to camel cased params but I figured that would be restrictive if people already started using snake cased in the past 🤔

Is this causing problems for you in some fashion ? Or just an observation?

**Comment by jdalrymple** [comment]
Always down to improve things however, just explaining why it is like that atm.

**Comment by jdalrymple** [comment]
Thinking of releaseing 3.0.0 soon, besides this, are there any other aspects you think should be looked at before sending it out?

**Comment by Mr-Wallet** [comment]
That justification makes perfect sense to me. As long as nothing in the API takes a more arbitrary object, I suppose there's actually no reason to try and preserve property names that we know would be ignored.
